import { motion } from "motion/react";
import { X, AlertTriangle, Shield, TrendingUp, Clock, Download } from "lucide-react";
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell,
  RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,
  AreaChart, Area
} from "recharts";
import { ParsedAnalysisData, getSeverityColor, formatAnalysisDate } from "../utils/analysisUtils";

interface AnalysisDetailPopupProps {
  analysis: ParsedAnalysisData | null;
  isOpen: boolean;
  onClose: () => void;
}

const COLORS = ['#FF3864', '#FFB800', '#00FFFF', '#00FFB3', '#7A5CFF'];

export function AnalysisDetailPopup({ analysis, isOpen, onClose }: AnalysisDetailPopupProps) {
  if (!isOpen || !analysis) return null;

  const handleDownloadReport = () => {
    const reportContent = `
FORENSIC ANALYSIS REPORT
========================

File: ${analysis.fileName}
Analysis Date: ${formatAnalysisDate(analysis.analysisDate)}
Risk Level: ${analysis.metrics.riskLevel}
Security Score: ${analysis.metrics.securityScore}/100

SUMMARY:
${analysis.summary}

METRICS:
- Total Findings: ${analysis.metrics.totalFindings}
- Critical Issues: ${analysis.metrics.criticalIssues}
- Medium Risk Issues: ${analysis.metrics.mediumRiskIssues}
- Low Risk Issues: ${analysis.metrics.lowRiskIssues}

KEY FINDINGS:
${analysis.keyFindings.map((finding, idx) => `
${idx + 1}. ${finding.title} (${finding.severity})
   Description: ${finding.description}
   ${finding.recommendation ? `Recommendation: ${finding.recommendation}` : ''}
`).join('\n')}

Generated by AI-Powered Cyber Forensic Triage Tool
© 2025 FOSS Mysore – Confidential
`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `analysis-report-${analysis.fileName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center p-2 overflow-y-auto">
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black/80 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        className="relative w-full max-w-6xl min-h-0 my-4 bg-[rgba(28,31,38,0.95)] backdrop-blur-xl border border-[rgba(0,255,255,0.3)] rounded-2xl overflow-hidden"
      >
        {/* Compact Header */}
        <div className="flex items-center justify-between p-4 border-b border-[rgba(0,255,255,0.2)] flex-shrink-0">
          <div className="flex items-center gap-3 min-w-0">
            <div className="flex items-center gap-2 min-w-0">
              <AlertTriangle 
                className="w-5 h-5 flex-shrink-0" 
                style={{ color: getSeverityColor(analysis.metrics.riskLevel) }}
              />
              <h2 className="text-lg text-[#E6E8EB] truncate">{analysis.fileName}</h2>
            </div>
            <div 
              className="px-2 py-1 rounded text-xs font-bold whitespace-nowrap flex-shrink-0"
              style={{ 
                backgroundColor: `${getSeverityColor(analysis.metrics.riskLevel)}20`,
                color: getSeverityColor(analysis.metrics.riskLevel),
                border: `1px solid ${getSeverityColor(analysis.metrics.riskLevel)}40`
              }}
            >
              {analysis.metrics.riskLevel}
            </div>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <button
              onClick={handleDownloadReport}
              className="flex items-center gap-2 px-3 py-1.5 bg-[rgba(0,255,255,0.1)] border border-[rgba(0,255,255,0.3)] rounded-lg text-[#00FFFF] hover:bg-[rgba(0,255,255,0.2)] transition-colors text-sm"
            >
              <Download className="w-4 h-4" />
              Export
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-[#8B92A0] hover:text-white hover:bg-[rgba(255,255,255,0.1)] rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto">
          <div className="p-4">
            {/* Compact Summary Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="bg-[rgba(255,56,100,0.1)] border border-[rgba(255,56,100,0.3)] rounded-lg p-3"
              >
                <div className="flex items-center gap-2">
                  <AlertTriangle className="w-6 h-6 text-[#FF3864]" />
                  <div>
                    <p className="text-lg font-bold text-[#FF3864]">{analysis.metrics.criticalIssues}</p>
                    <p className="text-xs text-[#8B92A0]">Critical</p>
                  </div>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="bg-[rgba(255,184,0,0.1)] border border-[rgba(255,184,0,0.3)] rounded-lg p-3"
              >
                <div className="flex items-center gap-2">
                  <TrendingUp className="w-6 h-6 text-[#FFB800]" />
                  <div>
                    <p className="text-lg font-bold text-[#FFB800]">{analysis.metrics.totalFindings}</p>
                    <p className="text-xs text-[#8B92A0]">Total</p>
                  </div>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="bg-[rgba(0,255,255,0.1)] border border-[rgba(0,255,255,0.3)] rounded-lg p-3"
              >
                <div className="flex items-center gap-2">
                  <Shield className="w-6 h-6 text-[#00FFFF]" />
                  <div>
                    <p className="text-lg font-bold text-[#00FFFF]">{analysis.metrics.securityScore}</p>
                    <p className="text-xs text-[#8B92A0]">Score</p>
                  </div>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="bg-[rgba(139,146,160,0.1)] border border-[rgba(139,146,160,0.3)] rounded-lg p-3"
              >
                <div className="flex items-center gap-2">
                  <Clock className="w-6 h-6 text-[#8B92A0]" />
                  <div>
                    <p className="text-xs font-bold text-[#E6E8EB]">{formatAnalysisDate(analysis.analysisDate)}</p>
                    <p className="text-xs text-[#8B92A0]">Date</p>
                  </div>
                </div>
              </motion.div>
            </div>

            {/* Compact Charts Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-6">
              {/* Vulnerability Types Bar Chart */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.5 }}
                className="bg-[rgba(28,31,38,0.6)] border border-[rgba(0,255,255,0.2)] rounded-lg p-4"
              >
                <h3 className="text-base text-[#E6E8EB] mb-3">Vulnerability Types</h3>
                <ResponsiveContainer width="100%" height={250}>
                <BarChart data={analysis.chartData.vulnerabilityTypes}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(0,255,255,0.1)" />
                  <XAxis 
                    dataKey="name" 
                    stroke="#8B92A0" 
                    fontSize={12}
                    angle={-45}
                    textAnchor="end"
                    height={80}
                  />
                  <YAxis stroke="#8B92A0" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(28,31,38,0.9)",
                      border: "1px solid rgba(0,255,255,0.3)",
                      borderRadius: "8px",
                    }}
                  />
                  <Bar dataKey="value" fill="#00FFFF" />
                </BarChart>
              </ResponsiveContainer>
            </motion.div>

              {/* Severity Distribution Pie Chart */}
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.6 }}
                className="bg-[rgba(28,31,38,0.6)] border border-[rgba(122,92,255,0.2)] rounded-lg p-4"
              >
                <h3 className="text-base text-[#E6E8EB] mb-3">Severity Distribution</h3>
                <ResponsiveContainer width="100%" height={250}>
                <PieChart>
                  <Pie
                    data={analysis.chartData.severityDistribution}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ severity, count }) => `${severity}: ${count}`}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="count"
                  >
                    {analysis.chartData.severityDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={getSeverityColor(entry.severity)} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(28,31,38,0.9)",
                      border: "1px solid rgba(0,255,255,0.3)",
                      borderRadius: "8px",
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </motion.div>

              {/* Timeline Analysis */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.7 }}
                className="bg-[rgba(28,31,38,0.6)] border border-[rgba(0,255,179,0.2)] rounded-lg p-4"
              >
                <h3 className="text-base text-[#E6E8EB] mb-3">Analysis Timeline</h3>
                <ResponsiveContainer width="100%" height={250}>
                <AreaChart data={analysis.chartData.timelineData}>
                  <defs>
                    <linearGradient id="colorIssues" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#00FFB3" stopOpacity={0.8}/>
                      <stop offset="95%" stopColor="#00FFB3" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(0,255,255,0.1)" />
                  <XAxis dataKey="time" stroke="#8B92A0" />
                  <YAxis stroke="#8B92A0" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(28,31,38,0.9)",
                      border: "1px solid rgba(0,255,255,0.3)",
                      borderRadius: "8px",
                    }}
                  />
                  <Area 
                    type="monotone" 
                    dataKey="issues" 
                    stroke="#00FFB3" 
                    fillOpacity={1} 
                    fill="url(#colorIssues)" 
                  />
                </AreaChart>
              </ResponsiveContainer>
            </motion.div>

              {/* Compliance Radar */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.8 }}
                className="bg-[rgba(28,31,38,0.6)] border border-[rgba(122,92,255,0.2)] rounded-lg p-4"
              >
                <h3 className="text-base text-[#E6E8EB] mb-3">Compliance Analysis</h3>
                <ResponsiveContainer width="100%" height={250}>
                <RadarChart data={analysis.chartData.complianceData}>
                  <PolarGrid stroke="rgba(0,255,255,0.2)" />
                  <PolarAngleAxis 
                    dataKey="category" 
                    stroke="#8B92A0" 
                    fontSize={12}
                  />
                  <PolarRadiusAxis stroke="#8B92A0" domain={[0, 100]} />
                  <Radar 
                    name="Score" 
                    dataKey="score" 
                    stroke="#7A5CFF" 
                    fill="#7A5CFF" 
                    fillOpacity={0.3} 
                  />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(28,31,38,0.9)",
                      border: "1px solid rgba(0,255,255,0.3)",
                      borderRadius: "8px",
                    }}
                  />
                </RadarChart>
              </ResponsiveContainer>
              </motion.div>
            </div>

            {/* Compact Key Findings */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.9 }}
              className="bg-[rgba(28,31,38,0.6)] border border-[rgba(0,255,255,0.2)] rounded-lg p-4"
            >
              <h3 className="text-base text-[#E6E8EB] mb-4">Key Findings & Recommendations</h3>
              <div className="space-y-3">
                {analysis.keyFindings.map((finding, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 1 + index * 0.1 }}
                    className="border border-[rgba(0,255,255,0.1)] rounded-lg p-3"
                  >
                    <div className="flex items-start gap-3">
                      <div 
                        className="w-2.5 h-2.5 rounded-full mt-1.5 flex-shrink-0"
                        style={{ backgroundColor: getSeverityColor(finding.severity) }}
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-2">
                          <h4 className="text-sm text-[#E6E8EB] font-semibold">{finding.title}</h4>
                          <span 
                            className="px-2 py-0.5 rounded text-xs font-bold whitespace-nowrap"
                            style={{ 
                              backgroundColor: `${getSeverityColor(finding.severity)}20`,
                              color: getSeverityColor(finding.severity),
                              border: `1px solid ${getSeverityColor(finding.severity)}40`
                            }}
                          >
                            {finding.severity}
                          </span>
                        </div>
                        <p className="text-[#8B92A0] text-xs mb-2 leading-relaxed">{finding.description}</p>
                        {finding.recommendation && (
                          <p className="text-[#00FFFF] text-xs">
                            <strong>Recommendation:</strong> {finding.recommendation}
                          </p>
                        )}
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </motion.div>
    </div>
  );
}