import { useState, useEffect } from "react";
import { useLocation } from "react-router-dom";
import { motion } from "motion/react";
import { FileText, Download, Check, Clock } from "lucide-react";
import { GlowButton } from "./GlowButton";
import { readTextFileContent, exportToTxt, exportToPdf, exportToJson, TextFileInfo } from "../utils/fileUtils";

const reportSections = [
  { id: "overview", title: "Executive Overview", completed: true },
  { id: "evidence", title: "Evidence Summary", completed: true },
  { id: "anomalies", title: "Anomaly Analysis", completed: true },
  { id: "timeline", title: "Timeline of Events", completed: false },
  { id: "custody", title: "Chain of Custody", completed: true },
  { id: "recommendations", title: "Recommendations", completed: false },
];

export function ReportGenerator() {
  const location = useLocation();
  const state = (location.state || {}) as { selectedFile?: TextFileInfo };
  const selectedFileFromState = state.selectedFile;

  const [selectedSections, setSelectedSections] = useState(reportSections.map(s => s.id));
  const [selectedFile] = useState<TextFileInfo | undefined>(selectedFileFromState);
  const [fileContent, setFileContent] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoadingContent, setIsLoadingContent] = useState(false);

  useEffect(() => {
    const loadFileContent = async () => {
      if (selectedFile?.path) {
        setIsLoadingContent(true);
        try {
          const content = await readTextFileContent(selectedFile.path);
          setFileContent(content);
        } catch (error) {
          console.error('Error loading file content:', error);
          setFileContent('Error loading file content.');
        } finally {
          setIsLoadingContent(false);
        }
      }
    };

    loadFileContent();
  }, [selectedFile]);

  const toggleSection = (sectionId: string) => {
    setSelectedSections(prev =>
      prev.includes(sectionId)
        ? prev.filter(id => id !== sectionId)
        : [...prev, sectionId]
    );
  };

  const generateReport = (format: string) => {
    if (!selectedFile || !fileContent) {
      alert('No file selected or content not loaded');
      return;
    }

    setIsGenerating(true);
    
    const reportData = {
      fileName: selectedFile.name,
      filePath: selectedFile.path,
      generatedDate: new Date().toISOString(),
      sections: selectedSections,
      content: fileContent,
      investigator: 'AI Forensic System',
      timestamp: new Date().toLocaleString()
    };

    const reportContent = `
Forensic Investigation Report
=============================

File Analyzed: ${selectedFile.name}
Generated: ${new Date().toLocaleDateString()}
Investigator: AI Forensic System

${fileContent}

=============================
End of Report
Generated by AI-Powered Cyber Forensic Triage Tool
© 2025 FOSS Mysore – Confidential
`;

    setTimeout(() => {
      try {
        const filename = `forensic-report-${selectedFile.name.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}`;
        
        switch (format) {
          case 'pdf':
            exportToPdf(reportContent, filename);
            break;
          case 'txt':
            exportToTxt(reportContent, filename);
            break;
          case 'json':
            exportToJson(reportData, filename);
            break;
          default:
            exportToTxt(reportContent, filename);
        }
      } catch (error) {
        console.error('Error generating report:', error);
        alert('Error generating report. Please try again.');
      } finally {
        setIsGenerating(false);
      }
    }, 1500);
  };

  return (
    <div className="p-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-6"
      >
        <h2 className="text-[#E6E8EB] mb-2">Report Generator</h2>
        <p className="text-sm text-[#8B92A0]">
          {selectedFile ? `Generating report for: ${selectedFile.name}` : 'Create comprehensive forensic reports'}
        </p>
        {isLoadingContent && (
          <p className="text-sm text-[#FFB800]">Loading file content...</p>
        )}
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Section Selection */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="bg-[rgba(28,31,38,0.6)] backdrop-blur-xl border border-[rgba(0,255,255,0.2)] rounded-2xl p-6"
        >
          <h3 className="text-[#E6E8EB] mb-4">Report Sections</h3>

          <div className="space-y-3 mb-6">
            {reportSections.map((section, index) => (
              <motion.div
                key={section.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                onClick={() => toggleSection(section.id)}
                className={`p-4 rounded-xl cursor-pointer transition-all ${
                  selectedSections.includes(section.id)
                    ? "bg-[rgba(0,255,255,0.1)] border-2 border-[#00FFFF]"
                    : "bg-[rgba(0,0,0,0.3)] border-2 border-[rgba(0,255,255,0.1)] hover:border-[rgba(0,255,255,0.3)]"
                }`}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div
                      className={`w-5 h-5 rounded border-2 flex items-center justify-center transition-all ${
                        selectedSections.includes(section.id)
                          ? "bg-[#00FFFF] border-[#00FFFF]"
                          : "border-[rgba(0,255,255,0.3)]"
                      }`}
                    >
                      {selectedSections.includes(section.id) && (
                        <Check className="w-3 h-3 text-[#0D1117]" />
                      )}
                    </div>
                    <p className="text-sm text-[#E6E8EB]">{section.title}</p>
                  </div>
                  {section.completed ? (
                    <Check className="w-4 h-4 text-[#00FFB3]" />
                  ) : (
                    <Clock className="w-4 h-4 text-[#FFB800]" />
                  )}
                </div>
              </motion.div>
            ))}
          </div>

          <div className="border-t border-[rgba(0,255,255,0.2)] pt-6">
            <h4 className="text-sm text-[#E6E8EB] mb-4">Export Format</h4>
            <div className="grid grid-cols-3 gap-3">
              <GlowButton
                onClick={() => generateReport("pdf")}
                variant="primary"
                className="text-sm py-2"
                disabled={isGenerating || isLoadingContent}
              >
                <Download className="w-4 h-4 inline mr-1" />
                PDF
              </GlowButton>
              <GlowButton
                onClick={() => generateReport("txt")}
                variant="secondary"
                className="text-sm py-2"
                disabled={isGenerating || isLoadingContent}
              >
                <Download className="w-4 h-4 inline mr-1" />
                TXT
              </GlowButton>
              <GlowButton
                onClick={() => generateReport("json")}
                variant="accent"
                className="text-sm py-2"
                disabled={isGenerating || isLoadingContent}
              >
                <Download className="w-4 h-4 inline mr-1" />
                JSON
              </GlowButton>
            </div>
          </div>

          {isGenerating && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              className="mt-6 p-4 bg-[rgba(122,92,255,0.1)] border border-[rgba(122,92,255,0.3)] rounded-lg"
            >
              <div className="flex items-center gap-3">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                >
                  <FileText className="w-5 h-5 text-[#7A5CFF]" />
                </motion.div>
                <p className="text-sm text-[#E6E8EB]">Generating report with digital signature...</p>
              </div>
            </motion.div>
          )}

          <div className="mt-6 p-4 bg-[rgba(0,255,179,0.1)] border border-[rgba(0,255,179,0.3)] rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Check className="w-4 h-4 text-[#00FFB3]" />
              <p className="text-sm text-[#E6E8EB]">Digital Signature</p>
            </div>
            <p className="text-xs text-[#8B92A0]">
              Timestamp: {new Date().toISOString()}
            </p>
            <p className="text-xs text-[#8B92A0] font-mono mt-1">
              SHA-256: b5e9d2a...f8c3
            </p>
          </div>
        </motion.div>

        {/* Right: Live Preview */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="bg-[rgba(28,31,38,0.6)] backdrop-blur-xl border border-[rgba(0,255,255,0.2)] rounded-2xl p-6"
        >
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-[#E6E8EB]">Live Preview</h3>
            <span className="text-xs text-[#8B92A0] bg-[rgba(0,255,255,0.1)] px-3 py-1 rounded-full">
              {selectedSections.length} sections selected
            </span>
          </div>

          <div className="bg-white rounded-lg p-8 max-h-[700px] overflow-y-auto custom-scrollbar">
            {/* Report Header */}
            <div className="border-b-2 border-[#0D1117] pb-6 mb-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h1 className="text-3xl text-[#0D1117] mb-2">
                    Forensic Investigation Report
                  </h1>
                  <p className="text-sm text-gray-600">
                    {selectedFile ? `Analysis File: ${selectedFile.name}` : 'No file selected'}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-sm text-gray-600">Generated: {new Date().toLocaleDateString()}</p>
                  <p className="text-sm text-gray-600">Investigator: AI Forensic System</p>
                </div>
              </div>
            </div>

            {/* Preview Content */}
            {isLoadingContent ? (
              <div className="mb-6 text-center">
                <p className="text-gray-500">Loading file content...</p>
              </div>
            ) : fileContent ? (
              <div className="mb-6">
                <h2 className="text-xl text-[#0D1117] mb-3">Analysis Results</h2>
                <div className="bg-gray-50 p-4 rounded border text-sm">
                  <pre className="whitespace-pre-wrap text-gray-800 font-mono text-xs leading-relaxed">
                    {fileContent.substring(0, 2000)}...
                  </pre>
                </div>
              </div>
            ) : selectedFile ? (
              <div className="mb-6">
                <h2 className="text-xl text-[#0D1117] mb-3">File Analysis</h2>
                <p className="text-sm text-gray-700">
                  Selected file: <strong>{selectedFile.name}</strong>
                </p>
                <p className="text-sm text-red-600">
                  Content could not be loaded. Please check the file path.
                </p>
              </div>
            ) : (
              <div className="mb-6">
                <h2 className="text-xl text-[#0D1117] mb-3">No File Selected</h2>
                <p className="text-sm text-gray-700">
                  Please go back and select a file to analyze.
                </p>
              </div>
            )}


            {/* Footer */}
            <div className="border-t-2 border-[#0D1117] pt-6 mt-6">
              <p className="text-xs text-gray-500 text-center">
                This report was generated by the AI-Powered Cyber Forensic Triage Tool
                <br />
                © 2025 FOSS Mysore – Confidential
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
