// File utility functions for handling text file operations

export interface TextFileInfo {
  name: string;
  path: string;
  content?: string;
}

// Get list of available text files from results directory
export const getAvailableTextFiles = async (): Promise<TextFileInfo[]> => {
  try {
    // In a real application, this would make an API call to the backend
    // For now, we'll simulate with the known files from the results directory
    const textFiles: TextFileInfo[] = [
      {
        name: "RPM Packages Backup",
        path: "/results/rpm-packages-backup.txt"
      },
      {
        name: "Security Key",
        path: "/results/security-key.txt"
      },
      {
        name: "Synthetic Vulnerability Inputs",
        path: "/results/synthetic_vuln_inputs.txt"
      },
      {
        name: "WiFi Passwords",
        path: "/results/wifi_passwords.txt"
      }
    ];
    
    return textFiles;
  } catch (error) {
    console.error('Error fetching text files:', error);
    return [];
  }
};

// Read content of a specific text file
export const readTextFileContent = async (filePath: string): Promise<string> => {
  try {
    // In a real application, this would make an API call to read the file content
    // For now, we'll simulate with mock content based on the file name
    const response = await fetch(`${filePath}`);
    if (response.ok) {
      return await response.text();
    }
    
    // Fallback with mock content for demo purposes
    return getMockFileContent(filePath);
  } catch (error) {
    console.error(`Error reading file ${filePath}:`, error);
    return getMockFileContent(filePath);
  }
};

// Mock content for demo purposes
const getMockFileContent = (filePath: string): string => {
  if (filePath.includes('rpm-packages-backup')) {
    return `RPM Packages Security Analysis Report
===========================================

Analysis Date: ${new Date().toLocaleDateString()}
Analyst: AI Forensic System

EXECUTIVE SUMMARY:
This analysis examines the RPM package backup for potential security vulnerabilities and anomalies.

FINDINGS:
- Total packages analyzed: 1,247
- Critical vulnerabilities found: 3
- Medium risk issues: 12
- Low risk issues: 28

CRITICAL VULNERABILITIES:
1. Package: openssl-1.0.2k-19.el7
   - CVE-2019-1547: ECDSA remote timing attack vulnerability
   - Recommendation: Update to latest version

2. Package: sudo-1.8.23-4.el7
   - CVE-2019-14287: Privilege escalation vulnerability
   - Recommendation: Immediate update required

3. Package: kernel-3.10.0-1062.el7
   - Multiple kernel vulnerabilities
   - Recommendation: System reboot required after update

MEDIUM RISK ISSUES:
- Outdated packages with known security issues
- Missing security patches for various components

RECOMMENDATIONS:
1. Immediate patching of critical vulnerabilities
2. Implement regular package update schedule
3. Monitor security advisories for installed packages

This report was generated by the AI-Powered Cyber Forensic Triage Tool.
Confidence Level: 94.2%`;
  }
  
  if (filePath.includes('security-key')) {
    return `Security Key Analysis Report
============================

Analysis Date: ${new Date().toLocaleDateString()}
Analyst: AI Forensic System

KEY DETAILS:
- Key Type: RSA-2048
- Creation Date: 2024-01-15
- Last Used: 2024-10-11
- Status: SUSPICIOUS ACTIVITY DETECTED

ANOMALIES DETECTED:
1. Unusual access patterns detected
2. Key used from multiple geographic locations
3. Access attempts outside normal business hours

GEOGRAPHIC ACCESS LOG:
- Primary Location: New York, NY (Normal)
- Secondary Access: Moscow, Russia (SUSPICIOUS)
- Tertiary Access: Beijing, China (HIGHLY SUSPICIOUS)

TIMELINE ANALYSIS:
- Normal usage: 09:00-17:00 EST
- Suspicious activity: 02:00-04:00 EST (Multiple attempts)

RISK ASSESSMENT: HIGH
Recommendation: Immediate key revocation and regeneration

This analysis indicates potential unauthorized access to the security key.
Immediate action required to prevent further compromise.`;
  }
  
  if (filePath.includes('synthetic_vuln_inputs')) {
    return `Synthetic Vulnerability Input Analysis
======================================

Analysis Date: ${new Date().toLocaleDateString()}
Analyst: AI Forensic System

INPUT VECTORS ANALYZED:
- SQL Injection attempts: 45
- Cross-Site Scripting (XSS): 23  
- Buffer Overflow patterns: 12
- Command Injection: 18
- Path Traversal: 8

SUCCESSFUL EXPLOITS:
1. SQL Injection on login form
   - Payload: ' OR 1=1 --
   - Result: Database access gained
   
2. XSS in comment section
   - Payload: <script>alert('XSS')</script>
   - Result: Script execution confirmed

3. Command Injection in file upload
   - Payload: ; cat /etc/passwd
   - Result: System file access

SYSTEM VULNERABILITIES:
- Insufficient input validation
- Lack of parameterized queries
- Missing output encoding
- Weak file upload restrictions

IMPACT ASSESSMENT:
- Data exposure: HIGH
- System compromise: MEDIUM
- Business risk: HIGH

REMEDIATION STEPS:
1. Implement input validation and sanitization
2. Use parameterized database queries
3. Add proper output encoding
4. Strengthen file upload security
5. Regular security testing

Critical vulnerabilities require immediate attention.`;
  }
  
  if (filePath.includes('wifi_passwords')) {
    return `WiFi Password Security Analysis
===============================

Analysis Date: ${new Date().toLocaleDateString()}
Analyst: AI Forensic System

NETWORKS ANALYZED: 15
WEAK PASSWORDS FOUND: 8

CRITICAL FINDINGS:
1. Network: "HomeNetwork_2.4G"
   - Password: "password123"
   - Strength: VERY WEAK
   - Dictionary attack: VULNERABLE

2. Network: "Office_WiFi"
   - Password: "12345678"
   - Strength: EXTREMELY WEAK
   - Brute force time: < 1 minute

3. Network: "Guest_Network"
   - Password: "guest"
   - Strength: CRITICAL
   - Common password: YES

SECURITY RECOMMENDATIONS:
1. Use WPA3 encryption where possible
2. Implement strong password policies
3. Regular password rotation (every 90 days)
4. Disable WPS functionality
5. Enable MAC address filtering

COMPLIANCE ISSUES:
- Multiple networks fail security standards
- Guest network lacks proper isolation
- Default passwords still in use

RISK LEVEL: HIGH
Immediate password updates recommended for all identified networks.

This assessment reveals significant wireless security vulnerabilities
requiring immediate remediation.`;
  }
  
  return `File content not available for preview.
Please check the file path and try again.

File: ${filePath}
Status: Content could not be loaded`;
};

// Export report data to different formats
export const exportToTxt = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportToPdf = (content: string, filename: string) => {
  // For a real implementation, you'd use a PDF library like jsPDF
  // For now, we'll create a simple text file with PDF extension
  const blob = new Blob([content], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportToJson = (data: any, filename: string) => {
  const jsonData = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonData], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};